public enum ConversationIDs {
	
//	*** UI
	STATS,
	
//	*** HOUSE MSG IDs
	HOUSE__SUBSCRIPTION_REQUEST,
	HOUSE__SUBSCRIPTION_REQUEST2,
	HOUSE__CONFIRM_SUBSCRIPTION,
	HOUSE__UNSUBSCRIBE_REQUEST,
	HOUSE__TELL_ME_RATE,
	
//	*** POWERPLANT MSG IDs
	POWERPLANT__FORCE_UNSUBSCRIBE_HOUSE_ACTION,
	
	
//	*** APPLIANCE MSG IDs
//	APPLIANCE_HOUSE_CONSUMPTION_UPDATE,
	ADD_APPLIANCE,
	DELETE_APPLIANCE,
	APPLIANCE_CONSUMPTION_TICK,
	
	

	
//	*** MISC
	APP_QUIT,

}
